"""Build the three-file UCP menu contract from editable sources (Python stdlib only)."""
from pathlib import Path
import argparse
import base64
import json
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'menu-src'


def read_locale(path):
    # Locale files use JSON-quoted YAML scalars, avoiding a build dependency on PyYAML.
    entries = [line.split(':', 1) for line in path.read_text(encoding='utf-8').splitlines() if line.strip()]
    result = {key: json.loads(value) for key, value in entries}
    if len(result) != len(entries):
        raise ValueError(f'Duplicate locale key: {path}')
    return result


def data_url(path):
    mime = 'font/ttf' if path.suffix == '.ttf' else 'image/png'
    return f'data:{mime};base64,' + base64.b64encode(path.read_bytes()).decode('ascii')


def build(check=False):
    fallback = read_locale(ROOT / 'locale/en.yml')
    for path in (ROOT / 'locale').glob('*.yml'):
        locale = read_locale(path)
        if locale.keys() != fallback.keys():
            raise ValueError(f'Incomplete localization: {path}')
        for key, text in locale.items():
            if sorted(re.findall(r'\{\w+\}', text)) != sorted(re.findall(r'\{\w+\}', fallback[key])):
                raise ValueError(f'Localization parameters differ: {path}: {key}')
    core = (SOURCE / 'core.js').read_text(encoding='utf-8')
    generated = {
        'LOCALIZATION': 'const LOCALIZATION_FALLBACK = ' + json.dumps(fallback, ensure_ascii=False, indent=2) + ';',
        'PORTRAITS': 'const AI_PORTRAIT_DATA = ' + json.dumps({p.stem: data_url(p) for p in sorted((SOURCE / 'assets/portraits').glob('*.png'))}) + ';',
        'MISSING_PORTRAIT': 'const AI_PORTRAIT_MISSING = ' + json.dumps(data_url(SOURCE / 'assets/portrait-missing.png')) + ';',
    }
    for marker, content in generated.items():
        token = f'/* GENERATED_{marker} */'
        if core.count(token) != 1:
            raise ValueError(f'Expected exactly one {token}')
        core = core.replace(token, content)
    js = '// Generated by tools/build-menu.py. Edit menu-src/ and locale/ instead.\n' + core + '\n' + (SOURCE / 'compact-view.js').read_text(encoding='utf-8')
    css = '\n'.join((SOURCE / name).read_text(encoding='utf-8') for name in ['ai-swapper.css', 'ucp-controls.css', 'ucp-scrollbar.css'])

    def embed(match):
        path = (SOURCE / match[1]).resolve()
        if not path.is_relative_to(SOURCE):
            raise ValueError(f'Asset outside source directory: {path}')
        return 'url("' + data_url(path) + '")'

    css = re.sub(r'''url\(["']?(assets/[^"')]+)["']?\)''', embed, css)
    css = '/* Generated by tools/build-menu.py. Edit menu-src/ instead. */\n' + css
    for filename, content in [('ai-swapper.js', js), ('ai-swapper.css', css)]:
        destination = ROOT / 'menu' / filename
        if check:
            if destination.read_text(encoding='utf-8') != content:
                raise ValueError(f'Stale generated file: {destination}')
        else:
            destination.write_text(content, encoding='utf-8')
    print('Menu sources, localization and generated files are consistent.' if check else 'Built menu JS/CSS from canonical sources.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated files are out of date.')
    build(parser.parse_args().check)
